# Generated by Django 4.1.1 on 2022-09-23 07:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('cat_desc', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('discount', models.FloatField(verbose_name='Discount(Rs)')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='GST',
            fields=[
                ('gst_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('igst', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='IGST(%)')),
                ('hsn_code', models.IntegerField(unique=True, verbose_name='HSN Code(Unique GST code)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.category', unique=True, verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'GST',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('p_img', models.ImageField(upload_to='product', verbose_name='Image')),
                ('p_price', models.FloatField(verbose_name='Price')),
                ('product_stock', models.FloatField(verbose_name='Quantity(total)')),
                ('unit', models.CharField(max_length=100, verbose_name='Unit(each)')),
                ('reorder_level', models.FloatField(verbose_name='Stock(qty)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.category', verbose_name='Category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.discount', verbose_name='Discount(Rs)')),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.gst', verbose_name='GST(hsn code --> igst(%))')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendor.vendor', verbose_name='Vendor')),
            ],
        ),
    ]
